# Generated by Django 5.2.4 on 2025-07-06 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('productivity', 'Productivity'), ('workload', 'Workload'), ('patterns', 'Patterns'), ('recommendation', 'Recommendation'), ('context', 'Context')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('importance_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('action_required', models.BooleanField(default=False)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('related_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-importance_level'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('tasks_created', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('avg_completion_time', models.FloatField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('workload_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('total_estimated_hours', models.FloatField(default=0)),
                ('high_priority_count', models.IntegerField(default=0)),
                ('upcoming_deadlines_count', models.IntegerField(default=0)),
                ('ai_accuracy_score', models.FloatField(default=0)),
                ('ai_suggestion_acceptance_rate', models.FloatField(default=0)),
                ('ai_priority_accuracy', models.FloatField(default=0)),
                ('priority_distribution', models.JSONField(default=dict)),
                ('category_stats', models.JSONField(default=dict)),
                ('productivity_trend', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_a_user_id_02a715_idx'), models.Index(fields=['period_type'], name='analytics_a_period__d917ba_idx')],
                'unique_together': {('user', 'date', 'period_type')},
            },
        ),
    ]
