# Generated by Django 5.2.4 on 2025-07-06 23:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('ai_suggestions', models.BooleanField(default=True)),
                ('ai_prioritization', models.BooleanField(default=True)),
                ('ai_context_analysis', models.BooleanField(default=True)),
                ('working_hours_start', models.TimeField(default=datetime.time(9, 0))),
                ('working_hours_end', models.TimeField(default=datetime.time(17, 0))),
                ('default_task_view', models.CharField(default='list', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aianalysislog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='aianalysislog',
            name='tasks_aiana_user_id_b71893_idx',
        ),
        migrations.RemoveIndex(
            model_name='aianalysislog',
            name='tasks_aiana_success_777f87_idx',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
